### ISSUE TITLE
Creating meta data with ApiPath or ResourcePath using the DSL does nothing

### ISSUE THREAD

**Issue by jchannon** [yahehe/Nancy.Swagger#12]
If you have ApiPath/ResourcePath together or individually when the swagger-ui is run you don't see the meta data for the root route

@liddellj is aware of this as I showed him in Jabbr

```
    Describe["Home"] = description => description.AsSwagger(with =>
            {
                with.ApiPath("/");
                with.ResourcePath("/");
                with.Summary("The root of the API");
                with.Notes("This is the root of the API when no other segments are passed");
                with.PathParam<string>("name", "a person's name");
            });
```

**Comment by GraemeF** [comment]
I just ran into this as well - bit confusing!

**Comment by yahehe** [comment]
Closing due to age. If this problem continues to occur with the latest version then please open a new issue.

Thanks!

**Comment by jchannon** [comment]
I didn't realise this had been adopted. @khellang kept it quiet

Looking forward to it

Don't forget Nancy slack if you need pointers

**Comment by yahehe** [comment]
Will do, thanks!
