### ISSUE TITLE
Describing Get / ?

### ISSUE THREAD

**Issue by axio-marco** [yahehe/Nancy.Swagger#131]
Trying to document a module with a GET / route:

            Describe["Get"] = description => description.AsSwagger(
                with => with.Operation(
                    op => op.OperationId("Get")
                            .Summary("Summary")
                            .Description("Stuff")
                            .Response(r => r.Schema<IEnumerable<SomethingDto>>())));

However, I get the following exception:

    Swagger.ObjectModel.Builders.RequiredFieldException: 'Paths' is required.
    at Swagger.ObjectModel.Builders.SwaggerRootBuilder.Build()
    at Nancy.Swagger.Services.SwaggerMetadataProvider.GetSwaggerJson(NancyContext context)
    (...)

Am I missing something?

**Comment by axio-marco** [comment]
Ah, I found my mistake. The Metadata module must be in the same namespace. Really?! 
Can it be somehow configured?

Also I find it really limiting and a huge downside that each endpoint must configure a name. Isn't there an alternative? Why can't I map the route explicitly within the Metadata module?

**Comment by catcherwong** [comment]
@axio-marco Metadata module seems should be in the same namespace ! 

It based on [Nancy.Metadata.Modules.DefaultMetadataModuleConventions](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Metadata.Modules/DefaultMetadataModuleConventions.cs) !

**Comment by axio-marco** [comment]
Thank you, putting the classes in Metadata/* works out of the box, that's fine. I was not aware I had to search this one in the Nancy source :)

**Comment by jnallard** [comment]
I added some info about that to the wiki. Sorry about that!

I might recommend checking out the annotations approach:
https://github.com/yahehe/Nancy.Swagger/wiki/Nancy.Swagger-for-Nancy-v2#describing-using-nancyswaggerannotations
It's a little bit more limited in terms of what you can describe, but it does allow you to keep the route descriptions in the same class as the routes. You can even skip the naming of the Nancy routes (so long as the HTTP Method and Path match).

**Comment by axio-marco** [comment]
Thank you. I will stick with the Metadata class approach and subclassed NancyModule which now generates the Route Names automatically.

**Comment by jnallard** [comment]
Thanks! 

I'm going to close this to clean up the issues.
If you have any other questions or problems, feel free to reopen this or create a new one!
