### ISSUE TITLE
Ignore some public Model properties.

### ISSUE THREAD

**Issue by vincentparrett** [yahehe/Nancy.Swagger#150]
Using Nancy.Swagger.Annotations,  there doesn't seem to be a way to ignore any public properties that might be listed on the model class but not part of the public model interface.

A simple solution would be to add an Ignore bool property to the ModelPropertyAttribute, and check that when selecting properties from the type. Properties should probably also be ignored if they have JsonIgnore or  XmlIgnore attributes. 

I'm happy to submit a pull request to implement this.

**Comment by jnallard** [comment]
Sounds good to me. Feel free to implement!

**Comment by vincentparrett** [comment]
Ok, will look into it.

**Comment by yahehe** [comment]
Implemented by #152
