### ISSUE TITLE
2.0.54 push to NuGet failed

### ISSUE THREAD

**Issue by Liklainy** [yahehe/Nancy.Swagger#169]
## Expected Behavior
Version 2.0.54 with the last PR successfully pushed to NuGet

## Actual Behavior
Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.

## Steps to Reproduce the Problem

  1. https://ci.appveyor.com/project/yahehe/nancy-swagger/builds/22660562
  
## Specifications

  - Version: 2.0.53
  - Project: Nancy.Swagger

**Comment by jnallard** [comment]
@yahehe, can you check this out?

**Comment by yahehe** [comment]
Sorry, lost track of this and I can never remember my login for Nuget. Running a build now, we'll see if it works this time

**Comment by yahehe** [comment]
Publishing is working again @jnallard , thanks for reporting this @Liklainy, sorry for the slow turnaround.

The latest published version is `2.2.56-alpha`
