### ISSUE TITLE
Ideas about parts of spec which are not implemented yet

### ISSUE THREAD

**Issue by timschlechter** [yahehe/Nancy.Swagger#18]
Is there any metadata in Nancy available we could use for <code>authorizations</code> and <code>produces, consumes</code>? For example, might we use the registered <code>ResponseProcessors</code> to determine <code>produces</code>?

I was just wondering if you guys have any ideas about this already.

**Comment by yahehe** [comment]
Closing due to age. These options should be provided in the current version, if not please open a new issue.

Thanks!
