### ISSUE TITLE
Add support for File datatype

### ISSUE THREAD

**Issue by timschlechter** [yahehe/Nancy.Swagger#22]
As described in section 4.3.5 in https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md

I see two options here:
-  Apply this behaviour when parameter type equals <code>byte[]</code> (or maybe <code>System.IO.File</code>?)
-  Add a new value <code>File</code> or <code>FileUpload</code> to the <code>ParameterType</code> enum, and act on this

Any thoughts/ideas?

**Comment by yahehe** [comment]
Implemented by #80
