### ISSUE TITLE
Add support for Info object on resource listing

### ISSUE THREAD

**Issue by timschlechter** [yahehe/Nancy.Swagger#23]
See https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md#513-info-object

Maybe we could simply add a property to <code>SwaggerConfig</code> on which you can set these values?

**Comment by jnallard** [comment]
So this was added. 
I added it as a static function call to SwaggerMetadataProvider quickly, but if anyone wants to use a better design, they're welcome to refactor it.
