### ISSUE TITLE
Json a bit odd with list property

### ISSUE THREAD

**Issue by jchannon** [yahehe/Nancy.Swagger#36]
I'm not sure if this is correct or not, if you have a model that has a property that is a List<T> it produces the below JSON which I think is correct but in the swagger-ui it shows the below. I guess it appears like that as the Participant type and its properties are not included in the raw JSON. Maybe if it did it wouldnt appear odd in the UI. Thoughts?

```
properties: {
  Participants: {
    type: "array",
    items: {
      $ref: "Participant"
    },
  }
},
```

![capture](https://cloud.githubusercontent.com/assets/105126/3858474/2c196132-1f0e-11e4-94c8-8feca603517b.PNG)

**Comment by yahehe** [comment]
Closing due to age. If this problem continues to occur (I believe it should be fixed) with the latest version then please open a new issue.

Thanks!
