### ISSUE TITLE
XXXModule naming convention is required

### ISSUE THREAD

**Issue by rbirkby** [yahehe/Nancy.Swagger#53]
A 'Module' suffix on the NancyModule class is required when it should be ambivalent. So, `public class XXXModule : NancyModule {}` works, whereas `public class XXXController : NancyModule {}` does not.

For example, changing HomeModule to HomeController in Nancy.Swagger.Demo and then accessing `http://localhost:1234/api-docs`, I get:

``` json
{"swaggerVersion":"1.2","apis":[]}
```

versus the correct response of:

``` json
{"swaggerVersion":"1.2","apis":[{"path":"/users"}]}
```

**Comment by pinkli** [comment]
I've encountered the same issue and it takes me one day to try to figure out why, where my nancy module is HelloModule, and meta data is HelloModuleMeta.
Rename it to HelloMetadataModule works.
It's a little wired though, what if my nancy module is Hello?
