### ISSUE TITLE
Swagger 2.0

### ISSUE THREAD

**Issue by adamhathcock** [yahehe/Nancy.Swagger#57]
Hi,

I'm using the project and I'd like to help out as I think I want to make it a critical piece for a REST API.  Are there any plans for supporting Swagger 2.0?  I'm open to helping out on other parts as well.

Adam

**Comment by goodmorninggoaway** [comment]
@khellang are you taking pull requests? @adamhathcock and I are working on updating this for swagger 2.0.

**Comment by khellang** [comment]
Yes we are. Sorry I haven't had time to look at this :disappointed:

**Comment by jvanzella** [comment]
What is the status of this PR?  I need to use Swagger 2.0 to import our API into Azure API Management and would really like to use Nancy.

**Comment by adamhathcock** [comment]
I personally have given up.  At first, my focus at work shifted so I didn't need this right away.  Now, we're going all in on ASP.NET 5 since it's open sourced and there's a swagger library for that: https://github.com/domaindrivendev/Ahoy

**Comment by jnallard** [comment]
So @yahehe  and I have worked on incorporating the PR @adamhathcock made and it is currently part of the latest NuGet packages.
If you want to use it, you might have to reconfigure your metadata modules and use Nancy 1.4 (With Nancy 2.0 support coming soon), but it should work. If not, we can help figure it out.

It doesn't allow backwards compatibility with Swagger 1.2, so if you want that, just remain on the version of the NuGet package that supports it. 
If you want changes for that swagger spec, we can make another branch without the Swagger 2.0 additions.

**Comment by yahehe** [comment]
Closing this as we now support Swagger 2.0. Hopefully we are fully featured but if we're missing something feel free to open an issue or a pr!
