### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by danny-waite** [yahehe/Nancy.Swagger#59]
Hi guys,

Great project.  However I've spent all weekend trying to make it work as expected.

If I add SwaggerRoute attributes to the methods the output in /api-docs/[Module] changes but if I try to make use of the [Module]MetadataModule method I just get the default output.

I've uploaded a very basic demo project I created for reference here:

https://github.com/cloudified/NancySwaggerTest.git

The ultimate issue I'm trying to fight is when using swagger-codegen I'm getting the following:

ValidationError(resourceListing,apiVersion is required,ERROR)
ValidationError(apiDeclaration,apiVersion is required,ERROR)
ValidationError(apiDeclaration,basePath is required,ERROR)

and I'm guessing the way I add those attributes is to use MetadataModule<SwaggerRouteData>

All help appreciated,
-- Danny

**Comment by jonnycoder** [comment]
Hi All @khellang - I see a lot of midnight oil has gone into this,  I'd like this work to be seen leveraged and appreciated in my organization.  I've downloaded the code and pulled up the built dist resource that points to Pet Store.  I'm scratching my head about how this code base generates its swagger.json file, any working examples to share or a few steps I'm missing?  I've spent half the day reading various threads so it's not for lack of trying, thanks!

**Comment by khellang** [comment]
Hey @danny-waite! Have you looked at [the sample](https://github.com/khellang/Nancy.Swagger/tree/master/samples/Nancy.Swagger.Demo)? There's not much documentation at the moment, and frankly I haven't had much time to prioritize this project :disappointed: There are two ways of defining metadata. You can do it using metadata modules, or attributes. I have no idea how far the attribute stuff has come, since I haven't really worked much on it. The installation should be really simple, just pull down [the NuGet package](https://www.nuget.org/packages/Nancy.Swagger), add metadata modules to describe your routes, and hit `/api-docs`. That should get you the json. If you want to add swagger-ui as well, you have to add that manually right now.

**Comment by TimSchlechter** [comment]
Hey @khellang. Just bumped into this issue. I haven't spent much time in this project lately, but can try to pick some things up again. I think we got pretty far, just need to add some little things and some examples/docs to make setup a bit easier.

I will try to add a demo project for the attribute-approach, it should'nt be that much work.

As I recall I needed PR #56 to make the general solution a bit more extendible, so one could extend things outside this package to pickup metadata from other attributes/source, like from Json.net. Would you mind looking into this PR if it's suitable to merge into master?

I'm also planning to dive  into Swagger 2.0, would be nice if we could support it.

**Comment by danny-waite** [comment]
hi guys, great to see some progress on this issue, I'm happy to assist wherever, so we can work towards a satisfactory point for everyone.

As outlined, I think if we could get things to a point where swagger-codegen can work this would be usable by most.

**Comment by danny-waite** [comment]
Hi all, I'm about to pick this back up again so wondered where things currently are before I dive back in.  Did you progress any?

**Comment by joelwilson** [comment]
I just went through the setup of Nancy.Swagger for a project. I stumbled through a few issues but got the `/api-docs` endpoint working in the end. I used the `MetaDataModule` method as opposed to the attributes method. I'll outline sorta what I did for future documentation purposes and anyone else that stumbles upon this issue like I did.

First, Install the Nancy.Swagger and Nancy.Metadata.Modules NuGet packages. 

For each of your Nancy modules, create a `MetadataModule` class. For example, for a module name `IndexModule` create a class called `IndexMetadataModule`. This class must inherit from `MetadataModule<SwaggerRouteData>`.

```
// IndexModule.cs
public class IndexModule : NancyModule
{
    public IndexModule()
    {
        Get["GetIndex", "/"] = parameters =>
        {
            return "It's working!";
        };
    }
}

// IndexMetadataModule.cs
public class IndexMetadataModule : MetadataModule<SwaggerRouteData>
{
    public IndexMetadataModule()
    {
        Describe["GetIndex"] = description => description.AsSwagger(with =>
        {
            with.ResourcePath("/");
            with.Summary("Gets the index.");
            with.Response(200, "Got the index.");
        });
    }
}
```

***Tip:*** Make sure your `*Module` and describing `*MetadataModule` classes are in the same namespace and that your `Describe` declarations have the same name as their corresponding routes.

Once you have your module metadata classes defined, start the project and go to `/api-docs` or `/api-docs.json`. This endpoint serves up json describing the API and can be consumed directly by [swagger-ui](https://github.com/swagger-api/swagger-ui) to display API documentation in a pretty way. I haven't tested this yet, but I believe it is doable.

**Comment by jiteshBhate** [comment]
is there any way this can be done via attribute , without creating ( *MetadataModule ).

**Comment by yahehe** [comment]
I don't think so, though I haven't looked into the attribute code much.

**Comment by yahehe** [comment]
@jiteshBhate if you're still interested in this then please check out the wiki, we're adding documentation on how to use this package (including annotations).
