### ISSUE TITLE
Nancy.Swagger up for adoption!

### ISSUE THREAD

**Issue by khellang** [yahehe/Nancy.Swagger#66]
Cross-posted from https://github.com/NancyFx/Nancy/issues/1486#issuecomment-125990112:

OK, I think it's time for me to put [Nancy.Swagger](https://github.com/khellang/Nancy.Swagger) up for adoption.

Here are my reasons:

I'm not using Nancy much for production (read; work) stuff anymore. Quite frankly, I don't do much server-side web *at all* ATM, so I've lost some interest :disappointed: 

I also lost quite a bit of steam realizing how much frickin' work it takes to get some decent metadata out of Nancy, simply because of its dynamic nature. Everything has to be explicitly declared, hand-holding the framework every step of the way, and I don't see this changing. Not very SDHP! :stuck_out_tongue_winking_eye:

And finally; time is a scarse, invaluable resource, and there are tons of things to do. Based on the above, I've concluded that spending huge amounts of my time on Nancy.Swagger is not really what I want. It's not fair to anyone that the project just sits there because I don't have interest or cycles to spend on it.

So... If someone would like to keep working on it, or simply scrap it altogether and use the name for a new project, just shout out, and I'll transfer the repository and NuGet package owner rights. :smile:

Thanks! :dancers:

**Comment by adamhathcock** [comment]
While I see myself using this soon, I also cannot devote time to be the maintainer either.  I will definitely contribute once my roadmap reaches the API documentation phase.

**Comment by jjchiw** [comment]
I'm using it in a dev environment and it's working fine, It covers all the needs we have.... I can view the issues that are right now and see if I can solve one, If I can I would like to help more actively with the project maybe not as owner but more as a contributor...

Thanks for the library

**Comment by dealproc** [comment]
would it be worthwhile to have this added to the Nancy organization?

**Comment by khellang** [comment]
I'm not sure what it'd buy us?

**Comment by pawelsawicz** [comment]
Hey,

@khellang I might jump in because in our work we use extensively Nancy, and I am done with manually updating those schemes :D.

**Comment by khellang** [comment]
@pawelsawicz Great! Do you want me to transfer ownership of this project to you, or just give you contributor rights? I'm curious... how do you plan to *not* manually update schemas? Because of Nancy's dynamic nature, you're forced to provide a bunch of metadata in order to generate Swagger metadata.

**Comment by dariusdamalakas** [comment]
Hey,

Just pinging that we are potentially looking at using Nancy in the future. We are transitioning to microservice architecture (40 microservices as of now), all of our services are WebApi, but we are evaluating the option of supporting Nancy as well. Swagger documentation will is a must, so we will definitely be looking at this package. We need swagger 2.0 support. Just letting you guys know that there are eyes looking at this project :)

**Comment by yahehe** [comment]
Has ownership of this repo been transferred yet? If not I would be willing to take it up, I've been using Nancy for the past year and would like to help ensure Nancy.Swagger moves forward

**Comment by nathanyeung** [comment]
@yahehe  I am also willing to help

**Comment by yahehe** [comment]
@khellang ?

**Comment by khellang** [comment]
@yahehe I'm unable to transfer ownership:

> yahehe/Nancy.Swagger already exists

**Comment by khellang** [comment]
Thanks to everyone offering a helping hand.æ! :heart: I'm transferring ownership to @yahehe and then he can take things from there. I will, of course, still be around for questions etc. :smile:

**Comment by yahehe** [comment]
Whoops, I've deleted my fork, should be good to go now?
