### ISSUE TITLE
Problem installing nuget package

### ISSUE THREAD

**Issue by FeodalherreN** [yahehe/Nancy.Swagger#74]
Install-Package : Could not install package 'Swagger.ObjectModel 2.1.0-alpha'. You are trying to install this package into a project that targets '.NETFramework,Version=vx.x', but the packag
e does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Swagger.ObjectModel -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I tried changing target framework a few times but without success. Any ideas? :)

**Comment by khellang** [comment]
Heh. I don't think you did anyone a favor by censoring the framework version: ".NETFramework,Version=vx.x". What version was it really?

**Comment by khellang** [comment]
For some reason, the latest (2.1.0-alpha) package only contains a `net462` target. You have to target that if you want to use the library.

**Comment by XLENTMarkus** [comment]
Thanks for the reply! I put x.x just to mark that i tried out a bunch of different targets. But the net462 response answers my question. Didn't have that option on the environment i was running, ill try install it and try it out.

**Comment by khellang** [comment]
Yeah, I see no reason why this library should target such a small audience. Very few run on .NET 4.6.2.

**Comment by yahehe** [comment]
Yep limiting it to 4.6.2 was unintentional, will try to remedy

**Comment by jnallard** [comment]
Yeah, I'm currently working on fixing this. 
New packages will be able to target multiple frameworks (4.0, 4.5, and 4.6.2 currently in my pr)

**Comment by yahehe** [comment]
The newest version, 2.1.1-alpha, is available now with the frameworks specified by @jnallard

**Comment by XLENTMarkus** [comment]
Thanks alot, I really appreciate the help! :)

**Comment by jnallard** [comment]
You're welcome! Sorry about the confusion.

I'm going to close this as it seems to be resolved.
