### ISSUE TITLE
Swagger-UI: redirect to the petstore

### ISSUE THREAD

**Issue by jnallard** [yahehe/Nancy.Swagger#88]
So rather than forcing people to include swagger-ui into the examples, we can simply redirect the user to the Swagger-UI petstore which can take a swagger doc url as a parameter.
e.g., http://petstore.swagger.io/?url=http://localhost:{port}/api-docs

This should make it easier for demonstrating. We can still add documentation for those wishing to include the swagger-ui on their nancy servers.

**Comment by yahehe** [comment]
Will that work with localhost?

**Comment by jnallard** [comment]
Yeah. I have a PR up and it was working for both sample projects. 

The calls are just made in your browser, so it will have access to your localhost.
