### ISSUE TITLE
Poor/No documentation for v1.4

### ISSUE THREAD

**Issue by theHurc** [yahehe/Nancy.Swagger#94]
I'm attempting to use Nancy.Swagger Version 2.1.1 with Nancy v1.4.3. There really isn't any documentation for this version so I have having trouble getting this set up, specifically, what should the Nancy bootstrapper look like to get this going. When I navigate to localhost:80/api-docs I get an error:

```
"Message":"Something went horribly, horribly wrong while servicing your request.","Details":"Nancy.RequestExecutionException: Oh noes! ---> Swagger.ObjectModel.Builders.RequiredFieldException: 'Paths' is required.\r\n   at Swagger.ObjectModel.Builders.SwaggerRootBuilder.Build()
```

No idea what I'm doing wrong. If anyone has some example code that would be great.

**Comment by yahehe** [comment]
Hi,

Sorry to hear you're having trouble, you can check out a sample on the 1.4.3 branch here: https://github.com/yahehe/Nancy.Swagger/tree/1.4.3-stable/samples/Nancy.Swagger.Demo

**Comment by jnallard** [comment]
If I remember correctly, I received the same error when I hadn't created any MetadataModules yet. 

As @yahehe said, that example should help! And the documentation for v2.0 is different, but there's definitely a lot that is still the same. (I still want to create more documentation for v1.4, so this ticket is a good reminder)

If you can't figure it out, feel free to post your code or a sample of your code and we can try to assist more.

**Comment by yahehe** [comment]
The documentation should be highly similar, the only thing that should really be different is the way Nancy creates routes in 2.0 vs 1.4.3. As long as you can adjust for that the samples should be identical

**Comment by theHurc** [comment]
@jnallard, I am attempting to use the Annotation method so I don't have any MetadataModules. Maybe I should attempt to use the MetadataModule version? Maybe I just misunderstand the usage.

@yahehe, I got the v2.0 Annotation example to work and I can hit the /api-docs route and it shows me the raw json just like I would expect. However, with the v1.4.3 example it doesn't have an Annotated example. If I run the example it opens the swagger-ui correctly but when I try to hit the route /api-docs it throws an exception. Is the Annotated method supported in v2.0?

**Comment by jnallard** [comment]
v2.1.1 for Nancy 1.4 is a little bit of a mess - It's a mix of an old PR to do swagger 2.0 and some extra additions that yahehe and I did.
When we were working on it and when yahehe took ownership of the repo, we weren't maintaining the Annotations project, so it's possible it's in a bad state. (Maybe we should remove that version of Annotations from Nuget for now)?
I did have to do a fair bit of work when I tried to use it in v2.2.

Is there a specific reason you want this version and not v2.2?
If you want this version, I'd recommend using the MetadataModules for now. If you really want v2.1.1, I can look into committing some time to fixing the Annotations project, (including making a sample project)

**Comment by theHurc** [comment]
@jnallard, thanks for the info. I was unable the get the Annotations for v2.1.1 to work so maybe it was never really completed. I forgot the exact reason I decided I didn't want to go to Nancy v2.0. I think maybe I didn't want .Net core in that package or something. Not sure. I'll look into it again.

The strange thing about the example in v1.4.3 is that the swagger-ui shows up fine but sending a GET request to `http://localhost:3999/swagger.json` or `http://localhost:3999/api-docs` throws an exception.

Anyway, thanks for your help. If I end up using v1.4.3 I'll try the MetadataModules, otherwise I'll just upgrade Nancy and use Nancy.Swagger v2.2.

Maybe try the Annotations in v1.4.3 and if you can't get them to work  remove that package and put a single line in the v1.4.3documentation. That may be helpful for the next unsuspecting victim! ;)

Thanks!

**Comment by yahehe** [comment]
You shouldn't have to include anything .Net Core if you don't want it, nuget should only pull down the framework version relevant to you (.Net Framework?).

I would definitely recommend just upgrading if possible, afaik Nancy v1.4.3 has little to no support right now as the community is gearing up for 2.0. I'll see if I can remove the Annotations.1.4.3 package from Nuget to avoid this in the future

**Comment by theHurc** [comment]
Oh that's good to know. Thanks!

**Comment by theHurc** [comment]
Quick update. I upgraded to the new Nancy version and got Nancy.Swagger.Annotations working in about 2 minutes!. Thanks again.
